apiVersion: batch/v1
kind: Job
metadata:
  name: neo4j-uploader
  namespace: etl
spec:
  template:
    spec:
      containers:
      - name: neo4j-uploader
        image: gbrunelli/neo4j_uploader:latest
      restartPolicy: OnFailure
