apiVersion: batch/v1
kind: Job
metadata:
    name: postgre-uploader
    namespace: etl
spec:
    template:
        spec:
            initContainers:
                - name: wait-for-postgres
                  image: busybox:latest
                  command:
                      - /bin/sh
                      - -c
                      - |
                          echo "Checking PostgreSQL service availability..."
                          until nc -z -v -w30 postgres.postgresql.svc.cluster.local 5432
                          do
                            echo "Waiting for PostgreSQL service to be available..."
                            sleep 5
                          done
                          echo "PostgreSQL service is available."
            containers:
                - name: postgre-uploader
                  image: opaulosoares/postgre_uploader:latest
                  env:
                      - name: POSTGRES_URI
                        value: "postgresql://postgres:helloworld@postgres.postgresql.svc.cluster.local:5432/distribuidos"
                  args:
                      - python
                      - /app/upload_to_postgre.py
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "100m"
                      limits:
                          memory: "256Mi"
                          cpu: "200m"
            restartPolicy: OnFailure
