# apiVersion: batch/v1
# kind: Job
# metadata:
#     name: neo4j-uploader
#     namespace: etl
# spec:
#     template:
#         spec:
#             initContainers:
#                 - name: wait-for-neo4j
#                   image: busybox:latest
#                   command:
#                       - /bin/sh
#                       - -c
#                       - |
#                           echo "Checking Neo4j service availability..."
#                           until nc -z -v -w30 neo4j-headless.neo4j.svc.cluster.local 7687
#                           do
#                             echo "Waiting for Neo4j service to be available..."
#                             sleep 5
#                           done
#                           echo "Neo4j service is available."
#             containers:
#                 - name: neo4j-uploader
#                   image: gbrunelli/neo4j_uploader:latest
#             restartPolicy: OnFailure

aapiVersion: batch/v1
kind: Job
metadata:
    name: postgres-uploader
    namespace: etl
spec:
    template:
        spec:
            initContainers:
                - name: wait-for-postgres
                  image: busybox:latest
                  command:
                      - /bin/sh
                      - -c
                      - |
                          echo "Checking PostgreSQL service availability..."
                          until nc -z -v -w30 postgres.postgresql.svc.cluster.local 5432
                          do
                            echo "Waiting for PostgreSQL service to be available..."
                            sleep 5
                          done
                          echo "PostgreSQL service is available."
            containers:
                - name: postgres-uploader
                  image: seu_usuario/postgres_uploader:latest
                  env:
                      - name: POSTGRES_URI
                        value: "postgresql://username:password@postgres.postgresql.svc.cluster.local:5432/your_database"
                  args:
                      - python
                      - /app/script_postgres.py
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "100m"
                      limits:
                          memory: "256Mi"
                          cpu: "200m"
            restartPolicy: OnFailure
