apiVersion: batch/v1
kind: Job
metadata:
    name: neo4j-uploader
    namespace: etl
spec:
    template:
        spec:
            initContainers:
                - name: wait-for-neo4j
                  image: busybox:latest
                  command:
                      - /bin/sh
                      - -c
                      - |
                          echo "Checking Neo4j service availability..."
                          until nc -z -v -w30 neo4j-headless.neo4j.svc.cluster.local 7687
                          do
                            echo "Waiting for Neo4j service to be available..."
                            sleep 5
                          done
                          echo "Neo4j service is available."
            containers:
                - name: neo4j-uploader
                  image: gbrunelli/neo4j_uploader:latest
            restartPolicy: OnFailure
