apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl-deployment
  namespace: etl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etl
  template:
    metadata:
      labels:
        app: etl
    spec:
      containers:
        - name: etl-container
          image: gbrunelli/spark_neo4j:latest
          command: ["spark-submit", "/app/spark_neo4j.py"]
          volumeMounts:
            - name: xls-file
              mountPath: /app/xls_conformidade_site_20240604_162827951.xls
              subPath: xls_conformidade_site_20240604_162827951.xls
      volumes:
        - name: xls-file
          hostPath:
            path: /path/on/host/xls_conformidade_site_20240604_162827951.xls
            type: File
