server:
    resources:
        requests:
            cpu: "500m"
            memory: "512Mi"
        limits:
            cpu: "1000m"
            memory: "1024Mi"

controller:
    resources:
        requests:
            cpu: "500m"
            memory: "512Mi"
        limits:
            cpu: "1000m"
            memory: "1024Mi"

repoServer:
    resources:
        requests:
            cpu: "250m"
            memory: "256Mi"
        limits:
            cpu: "500m"
            memory: "512Mi"

applicationController:
    resources:
        requests:
            cpu: "250m"
            memory: "256Mi"
        limits:
            cpu: "500m"
            memory: "512Mi"
