datasources:
    datasources.yaml:
        apiVersion: 1
        datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server
              access: proxy
              isDefault: true

# resources:
#     requests:
#         memory: "128Mi"
#         cpu: "100m"
#     limits:
#         memory: "256Mi"
#         cpu: "200m"

persistence:
    enabled: true
    size: 512Mi
    storageClassName: standard

service:
    type: LoadBalancer

ingress:
    enabled: false
