grafana:
    admin:
        existingSecret: grafana-admin-credentials

datasources:
    datasources.yaml:
        apiVersion: 1
        datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server
              access: proxy
              isDefault: true

persistence:
    enabled: true
    storageClassName: "standard"
    accessModes:
        - ReadWriteOnce
    size: 512Mi # Reduzido para 1Gi

service:
    type: LoadBalancer

ingress:
    enabled: false
