apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: backend
    namespace: argocd
    labels:
        name: backend
spec:
    project: default

    source:
        repoURL: https://github.com/GBrunelli/distributed-system
        targetRevision: HEAD
        path: ./services/backend/k8s

    destination:
        name: in-cluster
        namespace: backend

    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - Validate=false
            - CreateNamespace=true

        retry:
            limit: 10
            backoff:
                duration: 10s
                factor: 2
                maxDuration: 3m
