apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: postgresql
  labels:
    name: postgresql
spec:
  project: default

  source:
    repoURL: https://github.com/GBrunelli/distributed-system
    targetRevision: HEAD
    path: ./infrastructure/modules/postgresql

  destination:
    name: in-cluster
    namespace: postgresql

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true