apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark
  namespace: argocd
  labels:
    name: spark
spec:
  project: default

  source:
    repoURL: https://github.com/GBrunelli/distributed-system
    targetRevision: HEAD
    path: ./infrastructure/modules/spark

  destination:
    name: in-cluster
    namespace: spark

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true