apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: zookeeper
    namespace: argocd
    labels:
        name: zookeeper
spec:
    project: default

    source:
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 8.5.1
        chart: zookeeper

    destination:
        name: in-cluster
        namespace: kafka

    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - Validate=false
            - CreateNamespace=true

        retry:
            limit: 10
            backoff:
                duration: 10s
                factor: 2
                maxDuration: 3m

    values:
        replicaCount: 3
        image:
            registry: docker.io
            repository: bitnami/zookeeper
            tag: 3.6.2
        persistence:
            enabled: false
        resources:
            requests:
                memory: "256Mi"
                cpu: "100m"
            limits:
                memory: "512Mi"
                cpu: "200m"
