config:
    kafka:
        KAFKA_LISTENERS: PLAINTEXT://:9092,SASL_PLAINTEXT://:9093
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka.kafka.svc.cluster.local:9092,SASL_PLAINTEXT://kafka.kafka.svc.cluster.local:9093
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
        KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
        KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
        KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf

    extraVolumes:
        - name: kafka-server-jaas
          configMap:
              name: kafka-server-jaas

    extraVolumeMounts:
        - name: kafka-server-jaas
          mountPath: /etc/kafka/kafka_server_jaas.conf
          subPath: kafka_server_jaas.conf

resources:
    requests:
        memory: "4Gi"
        cpu: "2"
    limits:
        memory: "4Gi"
        cpu: "2"
