zookeeper:
  enabled: true
    persistence:
      enabled: false

persistence:
    enabled: false

provisioning:
  enabled: true
  topics:
    - name: request
      partitions: 1
      replicationFactor: 1
    - name: response
      partitions: 1
      replicationFactor: 1
