apiVersion: v1
kind: Service
metadata:
    labels:
        argocd.argoproj.io/instance: ui
    name: node-app-service
    namespace: ui
spec:
    ports:
        - nodePort: 7012
          port: 80
          protocol: TCP
          targetPort: 5000
    selector:
        app: node-app
    type: NodePort
