apiVersion: apps/v1
kind: Deployment
metadata:
    name: node-app-deployment
    labels:
        app: node-app
spec:
    replicas: 3
    selector:
        matchLabels:
            app: node-app
    template:
        metadata:
            labels:
                app: node-app
        spec:
            containers:
                - name: node-app
                  image: opaulosoares/dist_system_ui:latest
                  ports:
                      - containerPort: 5000
                  env:
                      - name: NODE_ENV
                        value: "production"

---
apiVersion: v1
kind: Service
metadata:
    name: node-app-service
spec:
    selector:
        app: node-app
    ports:
        - protocol: TCP
          port: 5012
          targetPort: 5000
    type: NodePort
