apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: gbrunelli/dist_system_ui:latest
        ports:
        - containerPort: 5173
        env:
        - name: NODE_ENV
          value: "production"